version: '2.4'

services:
  farm:
    build:
      context: ./server
      dockerfile: ./docker/server/Dockerfile
    volumes:
      - ./server/app:/app
      - ./server/data:/data
    environment:
      FARM_DATA: /data
    restart: unless-stopped

  celery:
    build:
      context: ./server
      dockerfile: ./docker/celery/Dockerfile
    volumes:
      - ./server/app:/app
      - ./server/data:/data
    environment:
      FARM_DATA: /data
    restart: unless-stopped

  front:
    build:
      context: ./server
      dockerfile: ./docker/front/Dockerfile
    restart: unless-stopped
    ports:
      - "5137:80"

  redis:
    image: redis:6.2.5-alpine
    ports:
      - "6378:6379"
    restart: unless-stopped
